<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AssemblyName>SeatSheet.Widget</AssemblyName>
    <RootNamespace>SeatSheet.Widget</RootNamespace>
    <ApplicationIcon>Assets/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><Resource Include="Assets/app-icon.png"/><Resource Include="Assets/app.ico"/></ItemGroup>
  <ItemGroup><Resource Include="Assets/Icons/ui.svg"/></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SeatSheet.RollCall.Protocol/SeatSheet.RollCall.Protocol.csproj" />
    <PackageReference Include="ClassIsland.Shared.IPC" Version="2.1.0.1" />
  </ItemGroup>
</Project>
